### PR TITLE
fix(viz): flows counter it's wrong

### LINKED ISSUE #1894: Multiflow Routes counter - showing incorrect information
### Describe the Bug

Small issue with the Routes counter - not decrementing based on the deleted routes.

See recording

### Steps to Reproduce the Bug or Issue

1. Add several routes
2. Switch them to visible in canvas
3. Delete routes - see the Routes counter doesn't decrement

### Screenshots or Videos

Peek 2023-06-02 12-32

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

### LINKED ISSUE #1911: When deleting all routes, the last one stays in the code editor
### Describe the Bug

When deleting the last route, the code editor has it still displayed even after the route disappears from the canvas.

### Steps to Reproduce the Bug or Issue

1. create a route
2. delete the route - having none left
3. see the last route stayed in the code editor

### Screenshots or Videos

Screenshot from 2023-06-05 15-32-23

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

### PR DESCRIPTION
**Pull request by lordrip**
### Context
At this moment, there's a bug in regard to the flow counter that is not being updated whenever a flow it's deleted.

### Changes
- Break circular dependency between `FlowsStore` and `StepsService`
- Update the flow counter whenever a flow is deleted
- Add missing tests from `FlowsStore`

fixes: https://github.com/KaotoIO/kaoto-ui/issues/1894
fixes: https://github.com/KaotoIO/kaoto-ui/issues/1911

### CODE REVIEW

File: src/utils/utils.ts [hunk 1]
```diff
@@ -84,7 +83,7 @@ export function setDeepValue(obj: any, path: any, value: any) {
 export function shorten(str: string, maxLen: number, separator = ' ') {
   if (!str) return;
   if (str.length <= maxLen) return str;
-  return str.substr(0, str.lastIndexOf(separator, maxLen)) + '..';
+  return str.substring(0, str.lastIndexOf(separator, maxLen)) + '..';
 }
 
 export function truncateString(str: string, num: number) {
```
Comment (igarashitm) [inline src/utils/utils.ts:89]: Not specific to this PR, but wonder if this could be replaced with https://www.patternfly.org/v4/components/truncate

**Review by igarashitm — APPROVED** [review]

File: src/utils/utils.ts (hunk 1 above)
Comment (lordrip) [reply src/utils/utils.ts:89]: Yes, I agree, remove this function and use patternfly instead :ok_hand:
