### PR TITLE
fix(Visualization): position after dropping the first node.

### LINKED ISSUE #1096: Initial node drop changes position out of screen
### Describe the Bug

When you drag and drop a step onto the initial placeholder node, it looks like it disappears. If you zoom out and scroll you'll see that it's just gone somewhere else. This doesn't happen after you replace the step with another one, only for the initial node.

Might be related to the PR where we centered the node: https://github.com/KaotoIO/kaoto-ui/pull/1010

### Steps to Reproduce the Bug or Issue

1. Open Kaoto
2. Open the catalog
3. Drag and drop a step onto the placeholder node

### Screenshots or Videos

Kapture 2023-01-13 at 13 57 45

### Platform

- OS: macOS
- Browser: Chrome
- Version: 0.50.0-dev

### PR DESCRIPTION
**Pull request by mmelko**
In order to fix #1096 I had to revert #1010 and then tweak default Viewport configuration.

### CODE REVIEW

File: src/components/Visualization.tsx [hunk 1]
```diff
@@ -31,15 +30,16 @@ interface IVisualization {
...
+    // 80/2 means half of the size of the icon so the placeholder icon can be centered
+    x: window.innerWidth / 2 - 80 / 2,
+    y: (window.innerHeight - 77) / 2 - 80 / 2,
     zoom: 1.2,
   };
-
   const [isPanelExpanded, setIsPanelExpanded] = useState(false);
   const [, setReactFlowInstance] = useState(null);
-  const reactFlowWrapperRef = useRef<HTMLDivElement>(null);
+  const reactFlowWrapper = useRef(null);
```
Comment (kahboom) [inline src/components/Visualization.tsx:42]: Why was this removed?

Comment (mmelko) [reply src/components/Visualization.tsx:42]: this was a part of the reverting the PR: https://github.com/KaotoIO/kaoto-ui/pull/1010/files#diff-20fc6180949d2fcf17d991cc62c6be55e572335ea16c00c805dcf3c7a8a6089dL38

**Review by kahboom — APPROVED** [review]
