### PR TITLE
fix: Provide prev/next step when querying step catalog to the backend

### LINKED ISSUE #1246: Add more context to mini-catalog calls.
### Please describe the feature that you want to propose

When the mini-catalog opens, there is a call to the backend api like `http://....../api/v1/steps?dsl=KameletBinding&type=MIDDLE,END&namespace=default`

For https://github.com/KaotoIO/kaoto-backend/issues/224 I would like to have a bit more context. I would like to have the `id` of the previous and the following (if exists) steps to return a more accurate list of available steps.

I am going to add to the backend two more parameters to this endpoint https://kaotoio.github.io/kaoto-backend/api/index.html#api-StepResource-v1StepsGet

`previous-step` that should contain the `id` of the step immediately before the `+` button that opens the mini-catalog. If this is the first step of a branch, add the previous step too, the one that branches.
`following-step` that should contain the `id` of the step right after the `+` button, if such a step exists. If not, don't send it.

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #1246

### CODE REVIEW

File: src/components/VisualizationStep.tsx [hunk 1]
```diff
@@ -1,35 +1,29 @@
...
   const visualizationStore = useVisualizationStore();
-  const integrationJsonStore = useIntegrationJsonStore();
-  const visualizationService = new VisualizationService(integrationJsonStore, visualizationStore);
-  const stepsService = new StepsService(integrationJsonStore, nestedStepsStore, visualizationStore);
+  const visualizationService = new VisualizationService();
+  const stepsService = new StepsService();
   const showBranchesTab = VisualizationService.showBranchesTab(data.step);
   const showStepsTab = VisualizationService.showStepsTab(data);
   const supportsBranching = StepsService.supportsBranching(data.step);
+  const parentStepId = data.branchInfo?.parentStepUuid ?? undefined;
```
Comment (lordrip) [inline src/components/VisualizationStep.tsx:26]: [curious-question] shouldn't this be `undefined` if `branchInfo` is `undefined`? Maybe we don't need the `?? undefined` part

File: src/services/stepsService.ts [hunk 2]
```diff
@@ -286,6 +286,15 @@ export class StepsService {
     return flattenMembers.concat(children.length ? StepsService.flattenSteps(children) : children);
   }
 
+  getFollowingStep(stepUuid?: string) {
+    if (!stepUuid) return undefined;
+    const currentStepIdx = this.findStepIdxWithUUID(stepUuid);
+    const steps = useIntegrationJsonStore.getState().integrationJson.steps;
+    return currentStepIdx !== -1 && steps.length > currentStepIdx + 1
```
Comment (lordrip) [inline src/services/stepsService.ts:293]: [side-comment] At the beginning I thought that we needed `steps.length >= currentStepIdx + 1` but after calculation, I think that it's ok 😄 

I went through this thought process:

Having this array: `[ 'a', 'b' ]`
**Case A:** Using `index=0` meaning `'a'`, for the condition `steps.length > currentStepIdx + 1` this would be `2 > 0 + 1` so yeah, 2 > 1.

**Case B:** Taking `'b'`, then it will be `2 > 1 + 1`, which is not `true` and it's ok since there's no additional step 🙆‍♂️

File: src/types/index.ts [hunk 3]
```diff
@@ -173,6 +173,8 @@ export interface IStepQueryParams {
   namespace?: string;
   // e.g. 'START', 'END', 'MIDDLE'
   type?: string;
+  'previous-step'?: string;
+  'following-step'?: string;
```
Comment (lordrip) [inline src/types/index.ts:177]: What are your thoughts about renaming these properties to the following? I think that would be easier to write a camel-cased version, there's an optional backend pull request if you want to do it: https://github.com/KaotoIO/kaoto-backend/pull/643

```suggestion
  'previousStep'?: string;
  'followingStep'?: string;
```

**Review by lordrip — DISMISSED** [review]
LGTM.

PS: The differences between Import sorting and code formatting from IntelliJ and VSCode makes me cry 😭

File: src/components/VisualizationStep.tsx (hunk 1 above)
Comment (igarashitm) [reply src/components/VisualizationStep.tsx]: fixned :+1:

File: src/types/index.ts (hunk 3 above)
Comment (igarashitm) [reply src/types/index.ts]: fixed :+1:

File: src/components/VisualizationStep.tsx [hunk 4]
```diff
@@ -1,35 +1,31 @@
...
-  const visualizationService = new VisualizationService(integrationJsonStore, visualizationStore);
-  const stepsService = new StepsService(integrationJsonStore, nestedStepsStore, visualizationStore);
+  const visualizationService = new VisualizationService();
+  const stepsService = new StepsService();
   const showBranchesTab = VisualizationService.showBranchesTab(data.step);
   const showStepsTab = VisualizationService.showStepsTab(data);
   const supportsBranching = StepsService.supportsBranching(data.step);
+  const parentStepId = data.branchInfo?.parentStepUuid
+    ? stepsService.findStepWithUUID(data.branchInfo.parentStepUuid)?.id ?? undefined
+    : undefined;
```
Comment (igarashitm) [inline src/components/VisualizationStep.tsx:28]: @lordrip so I was using `UUID` before and getting 400 error. Now this gets the parent step `ID` successfully.
