### PR TITLE
fix(beans): Restore default padding from the table row

### LINKED ISSUE #2003: Top of the editable field to add properties in beans configuration is cropped
### Describe the Bug

Top of the editable field to add properties in beans configuration is cropped

### Steps to Reproduce the Bug or Issue

1. Create a Camel route
2. Click beans
3. Click add beans
4. Click add string property
5. 

### Screenshots or Videos

image

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: kaoto snapshots

### PR DESCRIPTION
**Pull request by lordrip**
### Before
image

### After
image

fixes: https://github.com/KaotoIO/kaoto-ui/issues/2003

### CODE REVIEW

File: src/components/metadata/PropertyRow.tsx [hunk 1]
```diff
@@ -81,7 +81,6 @@ export function PropertyRow({
     <TreeRowWrapper
       key={`${propertyName}-${path.join('-')}`}
       row={{ props: treeRow!.props }}
-      className="propertyRow"
```
Comment (igarashitm) [inline src/components/metadata/PropertyRow.tsx:84]: Probably here as well...
https://github.com/KaotoIO/kaoto-ui/blob/ff6610c69084a89bfd6286dc249ebdb57cb0a22e/src/components/metadata/PropertyPlaceholderRow.tsx#L68

Comment (lordrip) [reply src/components/metadata/PropertyRow.tsx:84]: Done

**Review by igarashitm — APPROVED** [review]
