### PR TITLE
fix(stepsService): increment by 1 instead of 0.01

### LINKED ISSUE #1201: Spinner in config should increment by 1 instead of 0.01
### Please describe the feature that you want to propose

In most cases, the values are integer and not decimals

spinnerIssue

### PR DESCRIPTION
**Pull request by tplevko**
With the new version of uniforms-patternfly - it's possible now to specify schema with step value - set by default to 1.

Closes https://github.com/KaotoIO/kaoto-ui/issues/1201

### CODE REVIEW

**Review by igarashitm — DISMISSED** [review]

File: src/services/stepsService.ts [hunk 1]
```diff
@@ -663,6 +664,7 @@ export class StepsService {
         type,
         defaultValue,
         description,
+        ...(type === "number" || "integer") && {step : 1},
```
Comment (kahboom) [inline src/services/stepsService.ts:667]: Hey @tplevko there is one minor issue with deepscan that points this out, https://deepscan.io/dashboard/#view=project&tid=19033&pid=22364&bid=658659&subview=pull-request&prid=1623867

So, best thing here is probably to write it like `...(type === "number" || type === "integer") && {step : 1},` instead of `...(type === "number" || "integer") && {step : 1},`.

**Review by kahboom — CHANGES_REQUESTED** [review]
Minor point, otherwise everything looks great 👍

File: src/services/stepsService.ts (hunk 1 above)
Comment (tplevko) [reply src/services/stepsService.ts]: Thanks for pointing that out - updated

**Review by lordrip — APPROVED** [review]

**Review by kahboom — APPROVED** [review]
