### PR TITLE
Fix Kogito integration for empty files for which dirty marker was no

### LINKED ISSUE #158: Dirty marker does not appear anymore when opened file is empty
- open Kaoto editor
- add a step
--> the editor should become dirty and it is not

### PR DESCRIPTION
**Pull request by apupier**
more working

The IIntegration interface has been modified in
https://github.com/KaotoIO/kaoto-ui/commit/97f3d25d4ef7661b0a2bc5287d705fc4bd549b54 , the Kogito integration must be updated accordingly.

fixes kaotoio/vscode-kaoto#158

I don't know how to provide a test for this part of the code. I reported https://github.com/KaotoIO/vscode-kaoto/issues/159 to have at least a non-regression test for this use case at VS Code Kaoto level.

### CODE REVIEW

File: src/kogito-integration/KogitoEditorIntegrationProvider.tsx [hunk 1]
```diff
@@ -102,12 +102,13 @@ function KogitoEditorIntegrationProviderInternal(
...
 
         let intCopy = JSON.parse(JSON.stringify(integrationJson));
-        let tmpInt = {
+        const tmpInt: IIntegration = {
           ...integrationJson,
           metadata: {
             ...integrationJson.metadata,
             ...settings,
           },
+          dsl: settings.dsl.name
```
Comment (apupier) [inline src/kogito-integration/KogitoEditorIntegrationProvider.tsx:111]: what is fixing the issue is this line

File: src/kogito-integration/KogitoEditorIntegrationProvider.tsx [hunk 2]
```diff
@@ -102,12 +102,13 @@ function KogitoEditorIntegrationProviderInternal(
         }
 
         let intCopy = JSON.parse(JSON.stringify(integrationJson));
-        let tmpInt = {
+        const tmpInt: IIntegration = {
```
Comment (apupier) [inline src/kogito-integration/KogitoEditorIntegrationProvider.tsx:105]: modified here as it would have helped me to understand the code when I read it.

**Review by igarashitm — APPROVED** [review]

**Review by mmelko — APPROVED** [review]
