### PR TITLE
fix(CodeEditor): fix missing actions after cleanup the source code

### LINKED ISSUE #1132: Revert code editor to previous state
### Please describe the feature that you want to propose

We first need to fix the issue with data loss, which will require a discussion with UXD, but the current code editor is making for quite a bad user experience.

Previously, we used to be able to:
1) write the code, and it would render immediately

Now, we the process looks like this:
1) click the edit button (once you know where it is)
2) write the code
3) press the save button (once you know where it is)
4) close the success notification to be able to then
5) press the close button on the modal

That's an additional 4-5 steps that we didn't have to do before.

Ideally, we will fix the issue with data loss and revert to the previous state of the code editor, maybe with some additional handling of validation.

### LINKED ISSUE #1147: Clearing the code editor removes save & clear buttons
### Describe the Bug

If you press the clear button on the code editor (in edit mode) and then make changes, the save button disappears completely and you can't save at all. The same happens for the clear button.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Go to the code editor
2. Click edit mode
3. Press the clear button
4. Press "Start from scratch"
5. Make changes
6. The save button doesn't reappear

Repeat steps for the clear button.

### Screenshots or Videos

Code editor clear

### Platform

- OS: macOS
- Browser: Chrome
- Version: `0.6.1-dev`

### PR DESCRIPTION
**Pull request by mmelko**
disable CodeEditorModal and enable edit mode in a left panel again 
add default value for validationSchema in the settings
 hide left panel when settings are opened
fix #1132 
fix #1147

### CODE REVIEW

File: src/components/KaotoToolbar.tsx [hunk 1]
```diff
@@ -169,7 +170,10 @@ export const KaotoToolbar = ({ toggleCatalog, toggleCodeEditor }: IKaotoToolbar)
     <DropdownItem
       key="settings"
       data-testid={'kaotoToolbar-kebab__settings'}
-      onClick={() => setExpanded({ ...expanded, settingsModal: !expanded.settingsModal })}
+      onClick={() => {
```
Comment (kahboom) [inline src/components/KaotoToolbar.tsx:173]: Did you forget to remove this extra space? Just this is causing the code coverage to go down, which is so funny. 😂

File: src/components/SourceCodeEditor.tsx [hunk 2]
```diff
@@ -20,8 +14,9 @@ interface ISourceCodeEditor {
   language?: Language;
   theme?: string;
   mode?: CodeEditorMode | CodeEditorMode.FREE_EDIT;
+  schemaUri?: string;
   editable?: boolean | false;
-  editAction?: (code: string, event?: any) => void;
+  //01editAction?: (code: string, event?: any) => void;+-\
```
Comment (kahboom) [inline src/components/SourceCodeEditor.tsx:19]: Did you forget to remove this?

File: src/components/SourceCodeEditor.tsx [hunk 3]
```diff
@@ -99,12 +92,16 @@ const SourceCodeEditor = (props: ISourceCodeEditor) => {
   };
 
   const debounced = useDebouncedCallback((value: string) => {
-    // if editor is in read only mode file can be still uploaded.
-    if (props.mode !== CodeEditorMode.FREE_EDIT) {
+    if (props.mode == CodeEditorMode.TWO_WAY_SYNC) {
```
Comment (kahboom) [inline src/components/SourceCodeEditor.tsx:95]: Can we not use `===` here?

**Review by kahboom — CHANGES_REQUESTED** [review]
I've requested a few changes, but I also wanted to ask if we can add in a note to the user when the code editor is dirty, to ask them to save their changes and warn them about the loss of invalid data?

That way like with the old approach they know something is going to change in their code, and also that they need to save it. But it should only show once the editor is dirty.

File: src/components/SourceCodeEditor.tsx (hunk 3 above)
Comment (mmelko) [reply src/components/SourceCodeEditor.tsx:95]: did you mean `==` ? because that's what I'm using. If yes what should I use instead ?

Comment (apupier) [reply src/components/SourceCodeEditor.tsx:95]: usually in TypeScript and JavaScript world, we prefer to use the triple equal `===` instead of the double equal `==`. the double equal can do some weird type transformation.

Comment (apupier) [reply src/components/SourceCodeEditor.tsx:95]: https://rules.sonarsource.com/typescript/RSPEC-1440

**Comment by mmelko** [comment]
@kahboom  this will appear only if the code is different from the synced one and disappear after the sync or reverting the code.

Screenshot 2023-01-27 at 10 09 31

**Comment by mmelko** [comment]
@kahboom  this will appear only if the code is different from the synced one and disappear after the sync or reverting the code.

Screenshot 2023-01-27 at 10 09 31

File: src/components/SourceCodeEditor.tsx [hunk 4]
```diff
@@ -49,33 +48,29 @@ const SourceCodeEditor = (props: ISourceCodeEditor) => {
...
-    }
+    // update integration JSON state with changes
+    fetchIntegrationJson(incomingData, settings.dsl.name)
+      .then((res: IIntegration) => {
+        let tmpInt = res;
+        if (typeof res.metadata?.name === 'string' && res.metadata.name !== '') {
+          settings.name = res.metadata.name;
+          setSettings({ name: res.metadata.name });
+        }
+        tmpInt.metadata = { ...res.metadata, ...settings };
```
Comment (kahboom) [inline src/components/SourceCodeEditor.tsx:59]: Eventually we're gonna have to stop mutating so much data to prevent bugs :( this is my fault though for starting this lol

File: src/components/SourceCodeEditor.tsx (hunk 3 above)
Comment (kahboom) [reply src/components/SourceCodeEditor.tsx:97]: Yep it's what @apupier said

File: src/components/SourceCodeEditor.tsx [hunk 5]
```diff
@@ -175,37 +164,37 @@ const SourceCodeEditor = (props: ISourceCodeEditor) => {
...
-  } else if (props.mode === CodeEditorMode.FREE_EDIT && props.editable) {
-    customControls = [UndoButton, RedoButton, ClearButton, UpdateButton];
-  }
-
   return (
     <StepErrorBoundary>
+      {syncedCode !== sourceCode && (
+        <Alert
+          title="Any invalid code will be replaced after sync. If you don't want to lose your changes
+          please make a backup."
```
Comment (kahboom) [inline src/components/SourceCodeEditor.tsx:176]: What I was looking for was more a notice to let users know that they need to press the save button, not necessarily make a backup. They might not know it or even know where it is. I kind of wish we had a normal save button so it would be more obvious, but even a message would help.

**Review by kahboom — APPROVED** [review]
