### PR TITLE
 fix(1369,1370): fetch step details when inserting the step 

### LINKED ISSUE #1369: Missing config when inserting action step between existing start and end steps
### Describe the Bug

There are missing fields for middle "action" step, when it's inserted between two already specified start and end steps.

The config fields are visible when inserting prior to specifying the end step.

### Steps to Reproduce the Bug or Issue

1. specify start step
2. specify end step
3. specify middle action step - see there are no config fields present there

### Screenshots or Videos

Peek 2023-03-03 10-52

### Platform

- OS: [Linux]
- Browser: [Chrome,Firefox]
- Version: [latest]

### PR DESCRIPTION
**Pull request by mmelko**
fixes #1369 #1370

### CODE REVIEW

File: src/services/stepsService.ts [hunk 1]
```diff
@@ -335,30 +335,32 @@ export class StepsService {
...
-
-        this.integrationJsonStore.replaceBranchParentStep(
-          newParentStep,
-          currentStepNested.pathToParentStep
-        );
+        if (currentStepNested) {
+          const stepsCopy = this.integrationJsonStore.integrationJson.steps.slice();
+          let newParentStep = getDeepValue(stepsCopy, currentStepNested.pathToParentStep);
+          const newBranch = newParentStep.branches[currentStepNested.branchIndex];
+          const targetIdx = this.findStepIdxWithUUID(targetNode.data.step.UUID, newBranch.steps);
```
Comment (kahboom) [inline src/services/stepsService.ts:347]: @mmelko it's difficult to see what has been changed in this section, could it be something with the code formatting?

Comment (kahboom) [reply src/services/stepsService.ts:347]: Nevermind I see it was wrapped with an `if/else`

**Review by kahboom — APPROVED** [review]
